"""LLM-as-judge faithfulness scorer for the RAG pipeline.

Uses Gemini Flash to evaluate whether every claim in a generated response
is supported by the retrieved context.  Returns a score between 0.0 and 1.0.

This replaces the keyword-overlap heuristic in ``output_validator.py`` with
a semantically-aware evaluation that understands banking domain nuances.

Design decisions (spec T4-S9-02):
- Gemini Flash (not Lite) for judge quality while staying under 2s latency.
- Structured prompt returns JSON for reliable parsing.
- Fail-open on LLM errors: returns score=1.0 so the pipeline is not blocked.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from src.infrastructure.llm.client import GeminiClient

logger = logging.getLogger(__name__)

# ── Prompt ────────────────────────────────────────────────────────────

FAITHFULNESS_JUDGE_PROMPT = """\
You are a faithfulness evaluator for an enterprise banking RAG system.

Your task: determine whether EVERY claim in the RESPONSE is supported by the CONTEXT.

CONTEXT (retrieved banking documentation):
{context}

RESPONSE (generated by the RAG system):
{response}

Instructions:
1. Identify each factual claim in the RESPONSE.
2. For each claim, check if it is explicitly or implicitly supported by the CONTEXT.
3. Calculate a faithfulness score: (number of supported claims) / (total claims).
4. If the RESPONSE contains no factual claims (e.g., greetings, acknowledgments), score = 1.0.
5. If the RESPONSE is empty, score = 1.0.

Respond with ONLY a JSON object (no markdown, no explanation):
{{"score": <float between 0.0 and 1.0>, "reason": "<brief explanation in Spanish>"}}

Examples:
- All claims supported: {{"score": 1.0, "reason": "Todas las afirmaciones estan soportadas por el contexto."}}
- Some unsupported: {{"score": 0.5, "reason": "2 de 4 afirmaciones no tienen soporte en el contexto."}}
- Completely hallucinated: {{"score": 0.0, "reason": "Ninguna afirmacion tiene soporte en el contexto proporcionado."}}
"""

# ── Result dataclass ─────────────────────────────────────────────────


@dataclass(frozen=True, slots=True)
class FaithfulnessResult:
    """Result of LLM-as-judge faithfulness evaluation."""

    score: float
    is_faithful: bool
    reason: str
    raw_response: str = ""


# ── Judge class ──────────────────────────────────────────────────────


@dataclass
class FaithfulnessJudge:
    """LLM-as-judge that scores response faithfulness against context.

    Parameters
    ----------
    llm_client:
        GeminiClient configured with Flash for judge evaluation.
        If ``None``, scoring is skipped and score=1.0 is returned.
    threshold:
        Minimum faithfulness score (0.0-1.0).  Below this the response
        is considered unfaithful.  Default loaded from settings.
    """

    llm_client: GeminiClient | None = None
    threshold: float = 0.7

    async def evaluate(self, *, response: str, context: str) -> FaithfulnessResult:
        """Evaluate faithfulness of a response against context.

        Parameters
        ----------
        response:
            The LLM-generated text to evaluate.
        context:
            The RAG context (assembled chunks) the response should be
            faithful to.

        Returns
        -------
        FaithfulnessResult
            Contains the score, whether it passes threshold, and reason.
        """
        # Edge cases: empty inputs are vacuously faithful
        if not response or not response.strip():
            return FaithfulnessResult(
                score=1.0,
                is_faithful=True,
                reason="Respuesta vacia, considerada fiel por defecto.",
            )

        if not context or not context.strip():
            # No context to verify against — fail-open
            return FaithfulnessResult(
                score=1.0,
                is_faithful=True,
                reason="Sin contexto para verificar, se permite por defecto.",
            )

        if self.llm_client is None:
            logger.warning("faithfulness_judge: no LLM client, returning score=1.0")
            return FaithfulnessResult(
                score=1.0,
                is_faithful=True,
                reason="LLM client no disponible, fail-open.",
            )

        return await self._evaluate_with_llm(response=response, context=context)

    async def _evaluate_with_llm(self, *, response: str, context: str) -> FaithfulnessResult:
        """Call Gemini Flash to evaluate faithfulness."""
        assert self.llm_client is not None

        prompt = FAITHFULNESS_JUDGE_PROMPT.format(
            context=context,
            response=response,
        )

        try:
            raw_response = await self.llm_client.generate(prompt)
            return self._parse_response(raw_response.strip())
        except Exception:
            # Fail-open: if the judge LLM fails, let the response through
            logger.exception("faithfulness_judge: LLM evaluation failed, failing open")
            return FaithfulnessResult(
                score=1.0,
                is_faithful=True,
                reason="Error en evaluacion LLM, fail-open.",
            )

    def _parse_response(self, raw: str) -> FaithfulnessResult:
        """Parse the JSON response from the judge LLM.

        Handles common formatting issues: markdown code blocks, extra text.
        """
        cleaned = raw
        # Strip markdown code fences if present
        if cleaned.startswith("```"):
            lines = cleaned.split("\n")
            # Remove first and last line (``` markers)
            lines = [ln for ln in lines if not ln.strip().startswith("```")]
            cleaned = "\n".join(lines)
        cleaned = cleaned.strip()

        try:
            data = json.loads(cleaned)
            score = float(data.get("score", 0.0))
            reason = str(data.get("reason", ""))
        except (json.JSONDecodeError, TypeError, ValueError):
            logger.warning(
                "faithfulness_judge: failed to parse response, failing open: %.200s",
                raw,
            )
            return FaithfulnessResult(
                score=1.0,
                is_faithful=True,
                reason=f"Error parseando respuesta del judge: {raw[:200]}",
                raw_response=raw,
            )

        # Clamp score to [0.0, 1.0]
        score = max(0.0, min(1.0, score))
        is_faithful = score >= self.threshold

        return FaithfulnessResult(
            score=score,
            is_faithful=is_faithful,
            reason=reason,
            raw_response=raw,
        )
