apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: langfuse-secrets
  namespace: langfuse-test
# Para que este Secret use los valores locales de tu .env, realiza lo siguiente antes de aplicar este YAML:
# 1. Exporta las variables de tu .env en tu terminal:
#      export $(grep -v '^#' infra/langfuse/dev/.env | xargs)
# 2. Usa `envsubst` para reemplazar las variables en este YAML:
#      envsubst < infra/langfuse/dev/02.langfuse-secret.yaml | kubectl apply -f -
# Así, los valores definidos en tu .env local serán usados para crear el Secret.
stringData:
  salt: "${SALT}"
  encryption-key: "${ENCRYPTION_KEY}"
  nextauth-secret: "${NEXTAUTH_SECRET}"
  postgresql-password: "${POSTGRESQL_PASSWORD}"
  clickhouse-password: "${CLICKHOUSE_PASSWORD}"
  redis-password: "${REDIS_PASSWORD}"
  s3-user: "${S3_USER}"
  s3-password: "${S3_PASSWORD}"