"""add messages

Revision ID: a6e234523e27
Revises: 4f5c2df86346
Create Date: 2026-01-17 23:44:45.458872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6e234523e27'
down_revision: Union[str, Sequence[str], None] = '4f5c2df86346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('score', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_sources_message_id'), 'message_sources', ['message_id'], unique=False)
    op.add_column('messages', sa.Column('session_id', sa.UUID(), nullable=False))
    op.add_column('messages', sa.Column('user_role', sa.String(length=32), nullable=False))
    op.add_column('messages', sa.Column('direction', sa.String(length=16), nullable=False))
    op.add_column('messages', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.drop_constraint(op.f('messages_tenant_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_conversation_id_fkey'), 'messages', type_='foreignkey')
    op.drop_column('messages', 'tenant_id')
    op.drop_column('messages', 'conversation_id')
    op.drop_column('messages', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('role', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('messages_conversation_id_fkey'), 'messages', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key(op.f('messages_tenant_id_fkey'), 'messages', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.drop_column('messages', 'meta')
    op.drop_column('messages', 'direction')
    op.drop_column('messages', 'user_role')
    op.drop_column('messages', 'session_id')
    op.drop_index(op.f('ix_message_sources_message_id'), table_name='message_sources')
    op.drop_table('message_sources')
    # ### end Alembic commands ###
